spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3340/r2dbc
    username: root
    password: secret

#  webflux:
#    base-path: /r2dbc

server:
  port: 8081

cloud:
  aws:
    region:
      auto: false
      static: ap-northeast-1

    stack:
      auto: false
