name: example

on: [push]

jobs:
    build-gradle:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Setup Java
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - uses: actions/cache@v2
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
        - name: Cache Build Jar
          uses: actions/cache@v2
          with:
            path: build/libs
            key: ${{ runner.os }}-a
            restore-keys: |
              ${{ runner.os }}-a
        - name: build
          run: ./gradlew build -x test
